
import java.util.ArrayList;
import java.util.Random;
import static jdk.nashorn.internal.objects.NativeFunction.function;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Janek
 */
public class Rozmowa extends javax.swing.JPanel {

	/**
	 * Creates new form Rozmowa
	 */
	public Rozmowa() {
		this.ngram = new ArrayList();
		initComponents();
		ngram.add(input.getText());
		ngram.add("czesc");
		ngram.add("jak");
		ngram.add("sie");
		ngram.add("masz");
		ngram.add("dzien");
		ngram.add("dobry");
		ngram.add("pa");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextArea();
        button1 = new java.awt.Button();

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        display.setText("Odpowiedz tutaj");
        jScrollPane1.setViewportView(display);

        input.setColumns(20);
        input.setRows(5);
        input.setText("fh\nuu");
        jScrollPane2.setViewportView(input);

        button1.setLabel("wyślij");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
    }// </editor-fold>//GEN-END:initComponents
	
	ArrayList<String> ngram;
	ArrayList<String> wyniki;
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
		
		generate();
		
    }//GEN-LAST:event_button1ActionPerformed

	private int generate()
	{
		this.wyniki = new ArrayList();
		ArrayList<Integer> wyszukane = new ArrayList();
		Random generator = new Random(); 
		int ktorywyraz = generator.nextInt(ngram.size());
		
		display.setText(ngram.get(ktorywyraz));
		
		while(wyniki.size() < 15 && ktorywyraz+1 < ngram.size())
		{
			int znalezione = 0;
			wyszukane.clear();
			for (int i=0; i<ngram.size(); i++)
			{
				if((ngram.get(i)).equals(ngram.get(ktorywyraz)))
				{
					wyszukane.add(znalezione, i);
					znalezione++;
				}
			}
			if(znalezione!=0)
			{
				ktorywyraz = wyszukane.get(generator.nextInt(znalezione));
				while(ngram.get(ktorywyraz+1).endsWith("?"))
					ktorywyraz = wyszukane.get(generator.nextInt(znalezione));
				for(int i=1; i<2 ; i++)
				{
					wyniki.add(ngram.get(ktorywyraz+i));
				}
				ktorywyraz = ktorywyraz + 1;
			}
			else
			{
				return 0;
			}
		}
		wyniki.stream().forEach((_item) -> {
			display.setText(display.getText() + " " +_item);
		});
		return 0;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JTextArea display;
    private javax.swing.JTextArea input;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
